# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
start_profiler <- function(str) {
    .Call('_Rgperftools_start_profiler', PACKAGE = 'Rgperftools', str)
}

#' @export
stop_profiler <- function() {
    .Call('_Rgperftools_stop_profiler', PACKAGE = 'Rgperftools')
}

